services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - "MONGO_URI=mongodb://db:27017"
      - "FRONTEND_URL=http://frontend:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./gui
      dockerfile: Dockerfile
      args:
        - "REACT_APP_BACKEND_URL=http://backend:8080"
        - "REACT_APP_CLIENT_URL=http://localhost:6060"
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mongo:8
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
