services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - default
    environment:
      - "MONGO_URI=mongodb://db:27017"
      - "BACKEND_URL=backend:8080"
      - "FRONTEND_URL=frontend:3000"

  frontend:
    build:
      context: ./gui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - default
    environment:
      - BACKEND_URL=backend:8080

  db:
    image: mongo:8
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - default
